spring:
  datasource:
    url: jdbc:mysql://localhost/user_mgmt
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


server:
  servlet:
    context-path: /auth


jwt:
  secret: ${SECRET}
  access:
    token:
      validity: 3
  refresh:
    token:
      validity: 30